name: Consistent Pull Request

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  consistent-pull-request:
    name: Consistent Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Check head branch name
        uses: ./
        with:
          rules:
            feature/* bugfix/* refactor/* chore/* deps/*

      - name: Consistent pull request title and label
        if: >-
          github.event.action != 'synchronize' &&
          github.event.pull_request.state == 'open' &&
          github.head_ref != 'main'
        env:
          HEAD_REF: ${{ github.head_ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          label=$(echo "${HEAD_REF}" | cut -d'/' -f1)
          pr_title_regex="^\[${label}\]"
          if ! [[ "${PR_TITLE}" =~ ${pr_title_regex} ]]; then
            PR_TITLE="[${label}] ${PR_TITLE}"
          fi
          gh pr edit "${PR_NUMBER}" --title "${PR_TITLE}" --add-label "${label}"

      - name: Check base branch name
        uses: agaroot-technologies/action-restrict-base-branch@824225e012eff11d1d3f44ee5e862af2b7b5f1eb # v1.0.0
        with:
          rules:
            main <- feature/* bugfix/* refactor/* chore/* deps/*
